apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: predictive-maintenance-monitor
  labels:
    release: my-prometheus  # <--- THIS MUST MATCH THE OUTPUT FROM STEP 1
spec:
  selector:
    matchLabels:
      app: predictive-maintenance
  namespaceSelector:
    matchNames:
      - default
  endpoints:
  - port: http
    path: /metrics